name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        
      - name: Verify deployment
        if: success()
        run: |
          echo "Waiting for GitHub Pages to update..."
          sleep 30
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://etainkiely.github.io/etainkiely-com)
          echo "Deployment status: $HTTP_STATUS"
          if [ $HTTP_STATUS -ge 200 ] && [ $HTTP_STATUS -lt 400 ]; then
            echo "Deployment verified successfully!"
          else
            echo "Warning: Deployment verification returned status $HTTP_STATUS"
          fi

